name: gpt-transformer
channels:
  - anaconda
  - conda-forge
dependencies:
  - python==3.11.2
  - yapf==0.31.0
  - pylint==2.16.2
  - pip==23.0.1
  - pip:
      - torch==2.0.1
      - tiktoken==0.4.0
